### ISSUE TITLE
Clean up docs

### ISSUE THREAD

**Issue by andybak** [markfinger/python-webpack#13]
Hi,

I came across this trying to research good client-side build/deploy practices.

Your example code:

```
from django_webpack.compiler import webpack
bundle = webpack('path/to/webpack.config.js')
# Returns a string containing <script> elements pointing to the bundle
bundle.render()
```

My first thought was that this was meant to be used in management command that's run on a production server for every deploy. An extra step to run after 'collectstatic'...

But the fact that it returns a string makes it look like it's more like to be view code - or probably part of a templatetag.

Am I misunderstanding things?

**Comment by markfinger** [comment]
It's intended as to be plugged straight into templates during development, production integrations are up to the user, to be honest.

When deploying to prod, we build when restarting the process, and cache the output. It's probably not the best, but it's worked for our purposes.

You could easily integrate it into a more complicated build process, taking the file(s) generated and moving them about, but I haven't personally hit that need yet.

If there's a particular method or process that you recommend, you're more than welcome to make a PR to improve the docs/code.

**Comment by andybak** [comment]
OK. I'm already using django-compressor so maybe first of all I'll see how that integrates with webpack and then report back

**Comment by markfinger** [comment]
Partially dependent on #30

**Comment by markfinger** [comment]
Latest adds support for offline manifests, which adds support for dev/prod enviroments
