### ISSUE TITLE
Use in production

### ISSUE THREAD

**Issue by TheoRyley** [markfinger/python-webpack#33]
The dev branch differs a lot from the master, I'd like to know how you are currently using it in production. You mention in #32 that you are also using django-compressor. I'd like to know how you are integrating the two. Thanks.

**Comment by markfinger** [comment]
The comments in #32 and the related tickets were in reference to an aborted attempt to switch our shop's compressor-based pipeline to a purely webpack-based one. It ended up working well for CSS assets, but JS was getting messy - so I chose to continue using compressor, with webpack as a standalone part.

Back aways in the dev branch there were a couple of stabs at caching/manifest generation, but there was a pretty fundamental change in the consumption of config files, so it was all removed until things settled.

Current state is not really usable in prod. It'll depend on a live-connection to a server, and service tends to be sluggish on a cold boot with an empty cache.

**Comment by markfinger** [comment]
I've reopened #32 as I'll need this problem solved within the next week or so.
