### ISSUE TITLE
Needs compatibility with webpack-build 1.0.0

### ISSUE THREAD

**Issue by jbinney** [markfinger/python-webpack#37]
Noticed some changes in webpack-build 1.0.0 that requires changes in python-webpack as well (or at least in the documentation). From a quick test, running `node_modules/.bin/webpack-build` doesn't actually run the server anymore and outputs static files in the wrong location.

**Comment by markfinger** [comment]
Thanks for the heads up! It should be fixed now

**Comment by markfinger** [comment]
Spoke too soon: https://travis-ci.org/markfinger/python-webpack/builds/98595894

**Comment by markfinger** [comment]
Should be fixed now. webpack-build@1.0.1 added a few compatibility tweaks as well.

**Comment by jbinney** [comment]
Thanks Mark! Merry Christmas!
